version: '3.8'

services:
  cpu:
    build: 
      context: ./cpu
      dockerfile: Dockerfile
    image: cpu-monitor-image
    container_name: cpu-monitor
    ports:
      - "5678:5678"
    networks:
      - mynetwork

  apache:
    build: 
      context: ./apache
      dockerfile: Dockerfile
    image: apache-image 
    container_name: apache
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx-image
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
